WITH R AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) MX
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, R.MX AS FAVORITES
FROM REST_INFO RI
JOIN R
ON RI.FOOD_TYPE = R.FOOD_TYPE AND RI.FAVORITES = R.MX
ORDER BY RI.FOOD_TYPE DESC;