SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
LEFT JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE = 'Intact Male' AND AO.SEX_UPON_OUTCOME = 'Neutered Male'
OR
AI.SEX_UPON_INTAKE = 'Intact FeMale' AND AO.SEX_UPON_OUTCOME = 'Spayed Female'
ORDER BY AI.ANIMAL_ID