WITH T AS
(
    SELECT RI.REST_ID, ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
    FROM REST_INFO RI
    JOIN REST_REVIEW RR
    ON RI.REST_ID = RR.REST_ID
    WHERE SUBSTRING(RI.ADDRESS,1,2) = '서울'
    GROUP BY RI.REST_NAME
)


SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, T.SCORE
FROM REST_INFO RI
JOIN T
ON RI.REST_ID = T.REST_ID
ORDER BY SCORE DESC, RI.FAVORITES DESC;
