WITH T AS
(
    SELECT DISTINCT O.USER_ID, U.GENDER, YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, DATE_FORMAT(O.SALES_DATE,"%Y-%m") AS DATE
    FROM ONLINE_SALE O
    JOIN USER_INFO U
    ON O.USER_ID = U.USER_ID
    WHERE U.GENDER IS NOT NULL
)


SELECT YEAR, MONTH, GENDER, COUNT(GENDER) AS USERS
FROM T
GROUP BY DATE, GENDER
ORDER BY YEAR, MONTH, GENDER