# SELECT NAME, DATETIME
# FROM ANIMAL_INS
# WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
# ORDER BY DATETIME
# LIMIT 3

SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AI
LEFT JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.ANIMAL_ID IS NULL 
ORDER BY AI.DATETIME
LIMIT 3