WITH T AS(
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FO.AMOUNT * FP.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
)

SELECT PRODUCT_ID, PRODUCT_NAME, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM T
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID