SELECT B.CATEGORY AS CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(SALES_DATE) = '2022' and MONTH(SALES_DATE) = '1'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY