# SELECT FP.CATEGORY, F.MAX_PRICE, FP.PRODUCT_NAME
# FROM FOOD_PRODUCT FP
# JOIN (SELECT PRODUCT_ID, MAX(PRICE) AS MAX_PRICE
#     FROM FOOD_PRODUCT
#     WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
#     GROUP BY CATEGORY
#     HAVING MAX_PRICE) AS F
# ON FP.PRODUCT_ID = F.PRODUCT_ID
# ORDER BY FP.PRICE DESC;


SELECT FP.CATEGORY, FP.PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS F
ON FP.CATEGORY = F.CATEGORY AND FP.PRICE = F.MAX_PRICE
ORDER BY FP.PRICE DESC;